#pragma once
// ---------------------------------------------------------------------------
// Auto-generated by qbekun
// ---------------------------------------------------------------------------

#ifndef UNITYSDK_OFFSET
#define UNITYSDK_OFFSET(offset) offset
#endif

#define GAME_IMAGE_BASE 0x180000000ULL

// Battle
#define OFFSET_BATTLE_BEGIN                              UNITYSDK_OFFSET(0x125B170)  // Battle::Begin
#define OFFSET_BATTLE_UPDATE                             UNITYSDK_OFFSET(0x125C230)  // Battle::Update
#define OFFSET_BATTLE_PROCESSGAMEEND                     UNITYSDK_OFFSET(0x1260EC0)  // Battle::ProcessGameEnd

// LogicGameTime
#define OFFSET_LOGICGAMETIME_TICK                        UNITYSDK_OFFSET(0x1299760)  // LogicGameTime::Tick

// BattleEntity
#define OFFSET_BATTLEENTITY_ADDHITPOINT                  UNITYSDK_OFFSET(0x10FD830)  // BattleEntity::AddHitPoint
#define OFFSET_BATTLEENTITY_GET_HASMAINTARGET            UNITYSDK_OFFSET(0x10F7FB0)  // BattleEntity::HasMainTarget (get)

// HeroAction
#define OFFSET_HEROACTION_UPDATE                         UNITYSDK_OFFSET(0x10ED0C0)  // HeroAction::Update

// SummonedCharacter
#define OFFSET_SUMMONEDCHARACTER_UPDATE                  UNITYSDK_OFFSET(0x11507A0)  // SummonedCharacter::Update
#define OFFSET_SUMMONEDCHARACTER_EXPIRE                  UNITYSDK_OFFSET(0x1150770)  // SummonedCharacter::ExpireSummonedCharacter

// UIScenarioNew
#define OFFSET_UISCENARIONEW_GET_TASK                    UNITYSDK_OFFSET(0x27E19C0)  // UIScenarioNew::Task (get)

// PlayerSkillCardManager
#define OFFSET_SKILLCARDMANAGER_PROCESSSKILLCARD         UNITYSDK_OFFSET(0x1377EA0)  // PlayerSkillCardManager::ProcessSkillCard (player)
#define OFFSET_SKILLCARDMANAGER_UPDATEREGENCOST          UNITYSDK_OFFSET(0x1373750)  // PlayerSkillCardManager::UpdateRegenCost
#define OFFSET_SKILLCARDMANAGER_ADDCOST                  UNITYSDK_OFFSET(0x1373CA0)  // PlayerSkillCardManager::AddCost

// SkillCard
#define OFFSET_CHARACTERSKILLCARD_UPDATE                 UNITYSDK_OFFSET(0x1383950)  // SkillCard::Update (was CharacterSkillCard::Update)

// CurrentStat
#define OFFSET_STAT_TRYGETVALUE                          UNITYSDK_OFFSET(0x112F750)  // CurrentStat::TryGetValue
#define OFFSET_STAT_SETVALUE                             UNITYSDK_OFFSET(0x112FAB0)  // CurrentStat::SetValue

// BattleSceneHandler
#define OFFSET_BATTLESCENEHANDLER_UPDATE                 UNITYSDK_OFFSET(0x1D74DD0)  // BattleSceneHandler::Update
#define OFFSET_BATTLESCENEHANDLER_SET_BATTLESTATE        UNITYSDK_OFFSET(0x1D748F0)  // BattleSceneHandler::BattleState (set)
#define OFFSET_BATTLESCENEHANDLER_SET_BATTLERESULTSKIPTYPE UNITYSDK_OFFSET(0x1D74960)  // BattleSceneHandler::BattleResultSkipType (set)

